### ISSUE TITLE
Add hit counter to readme

### ISSUE THREAD

**Issue by SharkDemon** [SharkDemon/prominent-edge-assignment#1]

**Comment by the-amazing-atharva** [comment]
Hi!

I am a beginner here and would like to contribute
By Hit Counter you mean visit counts right?

Like this,
<a href="https://hits.seeyoufarm.com"><img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgithub.com%2FSharkDemon%2520%2Fprominent-edge-assignment&count_bg=%2379C83D&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false"/></a>
